# Generated by Django 5.2.6 on 2025-09-27 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('accuracy_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=255)),
                ('base_branch', models.CharField(max_length=255)),
                ('head_branch', models.CharField(max_length=255)),
                ('status', models.CharField(default='open', max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('github_url', models.URLField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('conflict_files', models.JSONField(default=list)),
                ('predicted_conflicts', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('github_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.CreateModel(
            name='FileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('change_type', models.CharField(max_length=20)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_removed', models.IntegerField(default=0)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_changes', to='core.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('risk_level', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('predicted_lines', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflicting_pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_with', to='core.pullrequest')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_predictions', to='core.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.pullrequest')),
            ],
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.repository'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'number')},
        ),
    ]
